export const seedUsers = [
  {
    id: "teacher-fisica-1",
    name: "Dra. Laura Mendoza",
    email: "laura.mendoza@universidad.edu",
    role: "TEACHER" as const,
  },
];

export const seedAuthors = [
  {
    id: "author-laura-mendoza",
    name: "Laura Mendoza",
    slug: "laura-mendoza",
    profession: "Fisica teorica",
    bio: "Docente universitaria enfocada en mecanica, oscilaciones y recursos didacticos interactivos.",
    avatarUrl: "/authors/mujer1.png",
  },
  {
    id: "author-carlos-ramirez",
    name: "Carlos Ramirez",
    slug: "carlos-ramirez",
    profession: "Ingeniero electrico",
    bio: "Profesor de electromagnetismo y circuitos con interes en visualizacion computacional.",
    avatarUrl: "/authors/hombre1.png",
  },
];

export const seedCourses = [
  {
    id: "course-fisica-ondas",
    title: "Fisica General II",
    slug: "fisica-general-ii",
    description: "Curso enfocado en ondas, oscilaciones, sonido y fenomenos de interferencia.",
    level: "INTERMEDIATE" as const,
    isPublished: true,
  },
];

export const seedTopics = [
  {
    id: "topic-ondas",
    title: "Ondas mecanicas",
    slug: "ondas-mecanicas",
    description: "Introduccion a amplitud, frecuencia, fase y velocidad de propagacion.",
    position: 1,
    courseId: "course-fisica-ondas",
  },
  {
    id: "topic-mas",
    title: "Movimiento armonico simple",
    slug: "movimiento-armonico-simple",
    description: "Resortes, energia y oscilaciones amortiguadas.",
    position: 2,
    courseId: "course-fisica-ondas",
  },
];

export const seedResources = [
  {
    id: "resource-video-ondas-1",
    title: "Introduccion a ondas mecanicas",
    slug: "introduccion-ondas-mecanicas",
    description: "Video introductorio para entender amplitud, frecuencia y longitud de onda.",
    type: "VIDEO" as const,
    category: "VIDEO" as const,
    status: "PUBLISHED" as const,
    storageUrl: "https://example.com/videos/ondas-intro",
    storageBucket: null,
    storagePath: null,
    originalFileName: "ondas-intro.mp4",
    mimeType: "video/mp4",
    thumbnailUrl: null,
    durationMinutes: 18,
    fileSizeMb: 240,
    publishedAt: new Date("2026-04-16T09:00:00.000Z"),
    authorId: "teacher-fisica-1",
    authorProfileId: "author-laura-mendoza",
    courseId: "course-fisica-ondas",
    topicId: "topic-ondas",
  },
  {
    id: "resource-pdf-ondas-1",
    title: "Guia PDF de ondas",
    slug: "guia-pdf-ondas",
    description: "Documento con teoria, ejercicios base y preguntas orientadoras.",
    type: "PDF" as const,
    category: "DOCUMENT" as const,
    status: "PUBLISHED" as const,
    storageUrl: "https://example.com/docs/guia-ondas.pdf",
    storageBucket: null,
    storagePath: null,
    originalFileName: "guia-ondas.pdf",
    mimeType: "application/pdf",
    thumbnailUrl: null,
    durationMinutes: null,
    fileSizeMb: 4.8,
    publishedAt: new Date("2026-04-15T12:00:00.000Z"),
    authorId: "teacher-fisica-1",
    authorProfileId: "author-laura-mendoza",
    courseId: "course-fisica-ondas",
    topicId: "topic-ondas",
  },
  {
    id: "resource-video-mas-1",
    title: "MAS y energia potencial",
    slug: "mas-y-energia-potencial",
    description: "Clase en video sobre resorte, periodo y conservacion de energia.",
    type: "VIDEO" as const,
    category: "VIDEO" as const,
    status: "DRAFT" as const,
    storageUrl: "https://example.com/videos/mas-energia",
    storageBucket: null,
    storagePath: null,
    originalFileName: "mas-energia.mp4",
    mimeType: "video/mp4",
    thumbnailUrl: null,
    durationMinutes: 24,
    fileSizeMb: 315,
    publishedAt: null,
    authorId: "teacher-fisica-1",
    authorProfileId: "author-carlos-ramirez",
    courseId: "course-fisica-ondas",
    topicId: "topic-mas",
  },
];
